"""add_session_id_to_snapshot

Revision ID: 0425218591b2
Revises: bfc3db3b55cf
Create Date: 2026-05-24 18:51:16.440589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0425218591b2'
down_revision: Union[str, Sequence[str], None] = 'bfc3db3b55cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_store', sa.Column('session_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_snapshot_store_session_id'), 'snapshot_store', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_store_session_id'), table_name='snapshot_store')
    op.drop_column('snapshot_store', 'session_id')
    # ### end Alembic commands ###
