"""create_reg_tables

Revision ID: 1003f36de196
Revises: 0425218591b2
Create Date: 2026-05-27 19:08:21.897093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1003f36de196'
down_revision: Union[str, Sequence[str], None] = '0425218591b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_nodes',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Enum('PROJECT', 'CONCEPT', 'PERSON', name='entitynodetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('degree_centrality', sa.Float(), nullable=False),
    sa.Column('hit_frequency', sa.Integer(), nullable=False),
    sa.Column('last_hit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ttl_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('node_id'),
    sa.UniqueConstraint('entity_name')
    )
    op.create_table('entity_edges',
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['entity_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['entity_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('edge_id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'relation_type', name='uq_entity_edges_source_target_relation')
    )
    op.create_table('node_hits',
    sa.Column('hit_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('hit_type', sa.Enum('QUERY', 'UPDATE', 'INFERENCE', name='hittype'), nullable=False),
    sa.Column('hit_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['entity_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('hit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_hits')
    op.drop_table('entity_edges')
    op.drop_table('entity_nodes')
    # ### end Alembic commands ###

