"""add_reg_indexes

Revision ID: af2cdb90cb73
Revises: 1003f36de196
Create Date: 2026-05-27 23:35:42.889647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2cdb90cb73'
down_revision: Union[str, Sequence[str], None] = '1003f36de196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_entity_nodes_entity_name', 'entity_nodes', ['entity_name'], unique=True)
    op.create_index('ix_entity_nodes_agent_id', 'entity_nodes', ['agent_id'], unique=False)
    op.create_index('ix_entity_nodes_ttl_expiry', 'entity_nodes', ['ttl_expiry'], unique=False)
    op.create_index('ix_entity_edges_source_target', 'entity_edges', ['source_node_id', 'target_node_id'], unique=False)
    op.create_index('ix_node_hits_node_id_timestamp', 'node_hits', ['node_id', 'hit_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_node_hits_node_id_timestamp', table_name='node_hits')
    op.drop_index('ix_entity_edges_source_target', table_name='entity_edges')
    op.drop_index('ix_entity_nodes_ttl_expiry', table_name='entity_nodes')
    op.drop_index('ix_entity_nodes_agent_id', table_name='entity_nodes')
    op.drop_index('ix_entity_nodes_entity_name', table_name='entity_nodes')
    # ### end Alembic commands ###
