"""initial_schema

Revision ID: afcedfacf8d9
Revises: 
Create Date: 2026-05-24 16:39:57.088368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from cortexgit.db.models import HAS_PGVECTOR


# revision identifiers, used by Alembic.
revision: str = 'afcedfacf8d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_postgres = (bind.dialect.name == "postgresql")

    if is_postgres:
        from sqlalchemy.dialects import postgresql
        import pgvector
        if HAS_PGVECTOR:
            # Create pgvector extension
            op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
            embedding_type = pgvector.sqlalchemy.vector.VECTOR(dim=1536)
        else:
            embedding_type = postgresql.ARRAY(sa.Float())
        
        event_id_type = sa.UUID()
        payload_type = postgresql.JSONB(astext_type=sa.Text())
        event_range_type = postgresql.INT4RANGE()
        entities_mentioned_type = postgresql.ARRAY(sa.Text())
    else:
        embedding_type = sa.Text()
        event_id_type = sa.UUID()
        payload_type = sa.Text()
        event_range_type = sa.String(255)
        entities_mentioned_type = sa.Text()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('event_id', event_id_type, nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Enum('SYSTEM', 'USER', 'AGENT', 'ACTION', 'OBSERVATION', 'THOUGHT', 'ERROR', name='eventtype'), nullable=False),
    sa.Column('payload', payload_type, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_log_agent_id'), 'event_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_event_log_session_id'), 'event_log', ['session_id'], unique=False)
    
    op.create_table('snapshot_store',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('event_range', event_range_type, nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('entities_mentioned', entities_mentioned_type, nullable=False),
    sa.Column('embedding', embedding_type, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    
    op.create_table('conflict_log',
    sa.Column('conflict_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('existing_value', payload_type, nullable=False),
    sa.Column('proposed_value', payload_type, nullable=False),
    sa.Column('existing_event_id', sa.UUID(), nullable=False),
    sa.Column('proposed_event_id', sa.UUID(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['existing_event_id'], ['event_log.event_id'], ),
    sa.ForeignKeyConstraint(['proposed_event_id'], ['event_log.event_id'], ),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    op.create_index(op.f('ix_conflict_log_key'), 'conflict_log', ['key'], unique=False)
    
    op.create_table('entity_registry',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', payload_type, nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_log.event_id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###

    # Enforce Append-Only and Immutability Triggers at DB Level
    if is_postgres:
        op.execute("""
            CREATE OR REPLACE FUNCTION prevent_update_delete()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'Updates and deletes are not allowed on this table';
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER enforce_event_log_append_only
            BEFORE UPDATE OR DELETE ON event_log
            FOR EACH ROW EXECUTE FUNCTION prevent_update_delete();
        """)
        op.execute("""
            CREATE TRIGGER enforce_snapshot_store_immutable
            BEFORE UPDATE ON snapshot_store
            FOR EACH ROW EXECUTE FUNCTION prevent_update_delete();
        """)
    else:
        op.execute("""
            CREATE TRIGGER enforce_event_log_append_only_update
            BEFORE UPDATE ON event_log
            BEGIN
                SELECT RAISE(FAIL, 'Updates and deletes are not allowed on this table');
            END;
        """)
        op.execute("""
            CREATE TRIGGER enforce_event_log_append_only_delete
            BEFORE DELETE ON event_log
            BEGIN
                SELECT RAISE(FAIL, 'Updates and deletes are not allowed on this table');
            END;
        """)
        op.execute("""
            CREATE TRIGGER enforce_snapshot_store_immutable
            BEFORE UPDATE ON snapshot_store
            BEGIN
                SELECT RAISE(FAIL, 'Updates and deletes are not allowed on this table');
            END;
        """)


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    is_postgres = (bind.dialect.name == "postgresql")

    if is_postgres:
        op.execute("DROP TRIGGER IF EXISTS enforce_snapshot_store_immutable ON snapshot_store;")
        op.execute("DROP TRIGGER IF EXISTS enforce_event_log_append_only ON event_log;")
        op.execute("DROP FUNCTION IF EXISTS prevent_update_delete();")
    else:
        op.execute("DROP TRIGGER IF EXISTS enforce_snapshot_store_immutable;")
        op.execute("DROP TRIGGER IF EXISTS enforce_event_log_append_only_update;")
        op.execute("DROP TRIGGER IF EXISTS enforce_event_log_append_only_delete;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_registry')
    op.drop_index(op.f('ix_conflict_log_key'), table_name='conflict_log')
    op.drop_table('conflict_log')
    op.drop_table('snapshot_store')
    op.drop_index(op.f('ix_event_log_session_id'), table_name='event_log')
    op.drop_index(op.f('ix_event_log_agent_id'), table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
